import type { Property } from "./types"

// Comprehensive property data similar to Homebazaar
export const allProperties: Property[] = [
  // Mumbai Properties
  {
    id: "lodha-park-worli",
    title: "Lodha Park - Luxury 3 BHK",
    description:
      "Experience luxury living at Lodha Park, Worli. This stunning 3 BHK apartment offers panoramic views of the Arabian Sea and Mumbai skyline. Premium amenities include infinity pool, spa, gym, and concierge services.",
    price: 85000000, // 8.5 Cr
    type: "sale",
    bedrooms: 3,
    bathrooms: 3,
    size: 1850,
    location: "Worli, Mumbai",
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Infinity Pool",
      "Spa & Wellness Center",
      "Gym & Fitness Center",
      "Concierge Services",
      "Valet Parking",
      "24/7 Security",
      "Kids Play Area",
      "Landscaped Gardens",
      "Club House",
      "Business Center",
    ],
    featured: true,
    createdAt: new Date("2024-01-15"),
    rating: 9,
    reviews: 45,
    developer: "Lodha Group",
    city: "mumbai",
  },
  {
    id: "oberoi-sky-city-borivali",
    title: "Oberoi Sky City - 2 BHK Premium",
    description:
      "Modern 2 BHK apartment in Oberoi Sky City, Borivali. Features contemporary design, premium fittings, and excellent connectivity to Western Express Highway and Borivali Railway Station.",
    price: 18500000, // 1.85 Cr
    type: "sale",
    bedrooms: 2,
    bathrooms: 2,
    size: 950,
    location: "Borivali West, Mumbai",
    image:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Swimming Pool",
      "Gym",
      "Jogging Track",
      "Kids Play Area",
      "Security",
      "Power Backup",
      "Parking",
      "Garden",
      "Club House",
      "Sports Courts",
    ],
    featured: true,
    createdAt: new Date("2024-01-20"),
    rating: 8,
    reviews: 32,
    developer: "Oberoi Realty",
    city: "mumbai",
  },
  {
    id: "hiranandani-fortune-city",
    title: "Hiranandani Fortune City - 1 BHK",
    description:
      "Affordable 1 BHK apartment in Hiranandani Fortune City, Panvel. Perfect for first-time homebuyers with modern amenities and excellent connectivity to Mumbai via Harbour Line.",
    price: 6800000, // 68 L
    type: "sale",
    bedrooms: 1,
    bathrooms: 1,
    size: 650,
    location: "Panvel, Mumbai",
    image:
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Swimming Pool",
      "Gym",
      "Garden",
      "Kids Play Area",
      "Security",
      "Parking",
      "Power Backup",
      "Water Storage",
      "Elevator",
      "Intercom",
    ],
    featured: false,
    createdAt: new Date("2024-01-25"),
    rating: 7,
    reviews: 28,
    developer: "Hiranandani Group",
    city: "mumbai",
  },
  {
    id: "kalpataru-paramount-thane",
    title: "Kalpataru Paramount - 3 BHK Duplex",
    description:
      "Spacious 3 BHK duplex in Kalpataru Paramount, Thane. Features double-height living room, private terrace, and premium specifications. Located near Ghodbunder Road with easy access to Mumbai.",
    price: 24500000, // 2.45 Cr
    type: "sale",
    bedrooms: 3,
    bathrooms: 3,
    size: 1650,
    location: "Thane West, Mumbai",
    image:
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Private Terrace",
      "Swimming Pool",
      "Gym",
      "Spa",
      "Kids Play Area",
      "Security",
      "Parking",
      "Garden",
      "Club House",
      "Tennis Court",
    ],
    featured: true,
    createdAt: new Date("2024-02-01"),
    rating: 9,
    reviews: 38,
    developer: "Kalpataru Group",
    city: "mumbai",
  },
  {
    id: "godrej-emerald-thane",
    title: "Godrej Emerald - 2 BHK Garden View",
    description:
      "Beautiful 2 BHK apartment with garden view in Godrej Emerald, Thane. Features modern kitchen, spacious bedrooms, and premium amenities in a gated community.",
    price: 16800000, // 1.68 Cr
    type: "sale",
    bedrooms: 2,
    bathrooms: 2,
    size: 1100,
    location: "Thane East, Mumbai",
    image:
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Garden View",
      "Swimming Pool",
      "Gym",
      "Yoga Deck",
      "Kids Play Area",
      "Security",
      "Parking",
      "Power Backup",
      "Rainwater Harvesting",
      "Waste Management",
    ],
    featured: false,
    createdAt: new Date("2024-02-05"),
    rating: 8,
    reviews: 25,
    developer: "Godrej Properties",
    city: "mumbai",
  },
  {
    id: "mahindra-lifespace-bandra",
    title: "Mahindra Lifespace - 4 BHK Penthouse",
    description:
      "Luxurious 4 BHK penthouse in Mahindra Lifespace, Bandra East. Features private pool, terrace garden, and panoramic city views. Premium location with easy access to BKC and airports.",
    price: 125000000, // 12.5 Cr
    type: "sale",
    bedrooms: 4,
    bathrooms: 4,
    size: 3200,
    location: "Bandra East, Mumbai",
    image:
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Private Pool",
      "Terrace Garden",
      "Home Automation",
      "Concierge Services",
      "Valet Parking",
      "Security",
      "Gym",
      "Spa",
      "Business Center",
      "Helipad Access",
    ],
    featured: true,
    createdAt: new Date("2024-02-10"),
    rating: 10,
    reviews: 15,
    developer: "Mahindra Lifespace",
    city: "mumbai",
  },

  // Pune Properties
  {
    id: "godrej-golf-links-greater-noida",
    title: "Godrej Golf Links - 3 BHK Villa",
    description:
      "Luxurious 3 BHK villa in Godrej Golf Links, Pune. Features private garden, golf course view, and premium amenities. Perfect for families seeking luxury living in a serene environment.",
    price: 32000000, // 3.2 Cr
    type: "sale",
    bedrooms: 3,
    bathrooms: 3,
    size: 2200,
    location: "Undri, Pune",
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Golf Course View",
      "Private Garden",
      "Swimming Pool",
      "Club House",
      "Gym",
      "Tennis Court",
      "Kids Play Area",
      "Security",
      "Parking",
      "Landscaped Gardens",
    ],
    featured: true,
    createdAt: new Date("2024-01-18"),
    rating: 9,
    reviews: 42,
    developer: "Godrej Properties",
    city: "pune",
  },
  {
    id: "kolte-patil-life-republic",
    title: "Kolte Patil Life Republic - 2 BHK",
    description:
      "Modern 2 BHK apartment in Kolte Patil Life Republic, Hinjewadi. Features contemporary design, smart home features, and excellent connectivity to IT parks and Mumbai-Pune Expressway.",
    price: 8500000, // 85 L
    type: "sale",
    bedrooms: 2,
    bathrooms: 2,
    size: 950,
    location: "Hinjewadi, Pune",
    image:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Smart Home Features",
      "Swimming Pool",
      "Gym",
      "Jogging Track",
      "Kids Play Area",
      "Security",
      "Parking",
      "Power Backup",
      "Broadband Ready",
      "Shopping Complex",
    ],
    featured: false,
    createdAt: new Date("2024-01-22"),
    rating: 8,
    reviews: 35,
    developer: "Kolte Patil",
    city: "pune",
  },
  {
    id: "sobha-rain-forest-kharadi",
    title: "Sobha Rain Forest - 3 BHK Premium",
    description:
      "Premium 3 BHK apartment in Sobha Rain Forest, Kharadi. Features spacious rooms, premium fittings, and world-class amenities. Located in the heart of Pune's IT corridor.",
    price: 14500000, // 1.45 Cr
    type: "sale",
    bedrooms: 3,
    bathrooms: 3,
    size: 1450,
    location: "Kharadi, Pune",
    image:
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Premium Fittings",
      "Swimming Pool",
      "Gym",
      "Spa",
      "Kids Play Area",
      "Security",
      "Parking",
      "Garden",
      "Club House",
      "Business Center",
    ],
    featured: true,
    createdAt: new Date("2024-01-28"),
    rating: 9,
    reviews: 29,
    developer: "Sobha Limited",
    city: "pune",
  },
  {
    id: "kumar-properties-baner",
    title: "Kumar Properties - 1 BHK Compact",
    description:
      "Compact 1 BHK apartment in Kumar Properties, Baner. Perfect for young professionals with modern amenities and excellent connectivity to IT parks and entertainment hubs.",
    price: 5200000, // 52 L
    type: "sale",
    bedrooms: 1,
    bathrooms: 1,
    size: 580,
    location: "Baner, Pune",
    image:
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Compact Design",
      "Swimming Pool",
      "Gym",
      "Kids Play Area",
      "Security",
      "Parking",
      "Power Backup",
      "Elevator",
      "Intercom",
      "Garden",
    ],
    featured: false,
    createdAt: new Date("2024-02-02"),
    rating: 7,
    reviews: 22,
    developer: "Kumar Properties",
    city: "pune",
  },
  {
    id: "tata-housing-avenida",
    title: "Tata Housing Avenida - 2 BHK",
    description:
      "Elegant 2 BHK apartment in Tata Housing Avenida, Ravet. Features modern architecture, premium amenities, and excellent connectivity to Mumbai-Pune Expressway.",
    price: 7800000, // 78 L
    type: "sale",
    bedrooms: 2,
    bathrooms: 2,
    size: 850,
    location: "Ravet, Pune",
    image:
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Modern Architecture",
      "Swimming Pool",
      "Gym",
      "Jogging Track",
      "Kids Play Area",
      "Security",
      "Parking",
      "Garden",
      "Club House",
      "Sports Courts",
    ],
    featured: false,
    createdAt: new Date("2024-02-08"),
    rating: 8,
    reviews: 31,
    developer: "Tata Housing",
    city: "pune",
  },

  // Rental Properties
  {
    id: "rent-luxury-apartment-powai",
    title: "Luxury 3 BHK Apartment in Powai",
    description:
      "Fully furnished luxury 3 BHK apartment in Powai with lake view. Features modern amenities, premium furnishing, and excellent connectivity to IT parks and airports.",
    price: 85000,
    type: "rent",
    bedrooms: 3,
    bathrooms: 3,
    size: 1500,
    location: "Powai, Mumbai",
    image:
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Fully Furnished",
      "Lake View",
      "Swimming Pool",
      "Gym",
      "Security",
      "Parking",
      "Power Backup",
      "Broadband",
      "Housekeeping",
      "Maintenance",
    ],
    featured: true,
    createdAt: new Date("2024-01-05"),
    rating: 9,
    reviews: 18,
    city: "mumbai",
  },
  {
    id: "rent-modern-flat-andheri",
    title: "Modern 2 BHK Flat in Andheri",
    description:
      "Semi-furnished 2 BHK flat in Andheri East with modern amenities. Close to metro station, shopping malls, and IT parks. Perfect for working professionals.",
    price: 55000,
    type: "rent",
    bedrooms: 2,
    bathrooms: 2,
    size: 950,
    location: "Andheri East, Mumbai",
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Semi Furnished",
      "Metro Connectivity",
      "Gym",
      "Security",
      "Parking",
      "Power Backup",
      "Elevator",
      "Intercom",
      "Garden",
      "Shopping Complex",
    ],
    featured: true,
    createdAt: new Date("2024-02-15"),
    rating: 8,
    reviews: 12,
    city: "mumbai",
  },
  {
    id: "rent-cozy-studio-bandra",
    title: "Cozy Studio Apartment in Bandra",
    description:
      "Compact studio apartment in Bandra West, perfect for young professionals. Fully furnished with modern amenities and close to restaurants, cafes, and nightlife.",
    price: 45000,
    type: "rent",
    bedrooms: 1,
    bathrooms: 1,
    size: 500,
    location: "Bandra West, Mumbai",
    image:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Fully Furnished",
      "Compact Design",
      "Security",
      "Parking",
      "Power Backup",
      "Broadband",
      "Housekeeping",
      "Maintenance",
      "Elevator",
      "Intercom",
    ],
    featured: false,
    createdAt: new Date("2024-03-10"),
    rating: 7,
    reviews: 8,
    city: "mumbai",
  },
  {
    id: "rent-spacious-3bhk-juhu",
    title: "Spacious 3 BHK Near Juhu Beach",
    description:
      "Spacious 3 BHK apartment near Juhu Beach with sea view. Semi-furnished with modern amenities, perfect for families. Close to schools, hospitals, and entertainment hubs.",
    price: 120000,
    type: "rent",
    bedrooms: 3,
    bathrooms: 3,
    size: 1800,
    location: "Juhu, Mumbai",
    image:
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Sea View",
      "Semi Furnished",
      "Swimming Pool",
      "Gym",
      "Security",
      "Parking",
      "Power Backup",
      "Garden",
      "Kids Play Area",
      "Beach Access",
    ],
    featured: false,
    createdAt: new Date("2024-04-05"),
    rating: 9,
    reviews: 15,
    city: "mumbai",
  },
  {
    id: "rent-premium-2bhk-baner",
    title: "Premium 2 BHK in Baner IT Hub",
    description:
      "Premium 2 BHK apartment in Baner IT hub area. Fully furnished with modern amenities, perfect for IT professionals. Close to major IT companies and entertainment zones.",
    price: 35000,
    type: "rent",
    bedrooms: 2,
    bathrooms: 2,
    size: 1100,
    location: "Baner, Pune",
    image:
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Fully Furnished",
      "IT Hub Location",
      "Swimming Pool",
      "Gym",
      "Security",
      "Parking",
      "Power Backup",
      "Broadband",
      "Housekeeping",
      "Club House",
    ],
    featured: true,
    createdAt: new Date("2024-02-20"),
    rating: 8,
    reviews: 14,
    city: "pune",
  },
  {
    id: "rent-modern-1bhk-kharadi",
    title: "Modern 1 BHK in Kharadi",
    description:
      "Modern 1 BHK apartment in Kharadi with contemporary design. Semi-furnished with all modern amenities, perfect for young professionals working in IT corridor.",
    price: 22000,
    type: "rent",
    bedrooms: 1,
    bathrooms: 1,
    size: 650,
    location: "Kharadi, Pune",
    image:
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Semi Furnished",
      "Modern Design",
      "Gym",
      "Security",
      "Parking",
      "Power Backup",
      "Elevator",
      "Intercom",
      "Garden",
      "Broadband Ready",
    ],
    featured: false,
    createdAt: new Date("2024-03-15"),
    rating: 7,
    reviews: 9,
    city: "pune",
  },
  {
    id: "rent-family-3bhk-hinjewadi",
    title: "Family 3 BHK in Hinjewadi Phase 2",
    description:
      "Spacious 3 BHK apartment in Hinjewadi Phase 2, perfect for families. Semi-furnished with excellent amenities and close to schools, hospitals, and IT parks.",
    price: 42000,
    type: "rent",
    bedrooms: 3,
    bathrooms: 3,
    size: 1350,
    location: "Hinjewadi, Pune",
    image:
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Semi Furnished",
      "Family Friendly",
      "Swimming Pool",
      "Gym",
      "Kids Play Area",
      "Security",
      "Parking",
      "Power Backup",
      "Garden",
      "School Nearby",
    ],
    featured: false,
    createdAt: new Date("2024-04-10"),
    rating: 8,
    reviews: 11,
    city: "pune",
  },
  {
    id: "rent-luxury-2bhk-koregaon",
    title: "Luxury 2 BHK in Koregaon Park",
    description:
      "Luxury 2 BHK apartment in prime Koregaon Park location. Fully furnished with premium amenities, close to restaurants, cafes, and entertainment hubs.",
    price: 65000,
    type: "rent",
    bedrooms: 2,
    bathrooms: 2,
    size: 1200,
    location: "Koregaon Park, Pune",
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    amenities: [
      "Fully Furnished",
      "Prime Location",
      "Swimming Pool",
      "Gym",
      "Security",
      "Parking",
      "Power Backup",
      "Housekeeping",
      "Concierge",
      "Entertainment Hub",
    ],
    featured: true,
    createdAt: new Date("2024-01-30"),
    rating: 9,
    reviews: 16,
    city: "pune",
  },
]

// Featured properties (subset of all properties)
export const featuredProperties = allProperties.filter((property) => property.featured === true)

// Properties by city
export const mumbaiProperties = allProperties.filter((property) => property.city === "mumbai")
export const puneProperties = allProperties.filter((property) => property.city === "pune")

// Properties by type
export const saleProperties = allProperties.filter((property) => property.type === "sale")
export const rentProperties = allProperties.filter((property) => property.type === "rent")
